### ISSUE TITLE
Stop supporting node 10?

### ISSUE THREAD

**Issue by sarbbottam** [sarbbottam/eslint-find-rules#125]
[eslint has dropped support for node < 4](https://github.com/eslint/eslint/blob/master/docs/user-guide/migrating-to-3.0.0.md#dropping-support-for-nodejs--4), Should eslint-find-rules do the same?

If not, [we have restrict the dependent eslint version < 3 to get the build pass](https://travis-ci.org/sarbbottam/eslint-find-rules/jobs/142552371#L198)

@ta2edchimp @ljharb thoughts?

**Comment by ljharb** [comment]
You're correct that in order to support both eslint 2 and 3, you'll have to conditionally install eslint 2 for node < 4 in travis, and eslint 3 for node >= 4.

Personally I think this is worth it to maintain back compat for awhile - if you disagree, then surely you'll want to drop support for pre-node-4. However, eslint 3 kept support for the eslint 2 rule format precisely to give eslint 2 users time to upgrade - and the longer eslint-find-rules supports both, the easier it will be for eslint 2 users to smoothly upgrade to eslint 3.

**Comment by ta2edchimp** [comment]
I'd definitely vote for keeping backwards compatibility for a while.
As I'd like to get the coloured output feature #52 also for ESLint 2 (in case it won't take us forever to realize it :stuck_out_tongue_winking_eye: ), how about another dist-channel to enable certain features and fixes for ESLint 2 users, while generally proceeding with version 2 (for ESLint 3)?
(I personally have zero experience in using the npm dist channels though ...)

**Comment by ljharb** [comment]
Small plug for using https://www.npmjs.com/package/safe-publish-latest to avoid accidental latest publishes when maintaining multiple version lines :-p

**Comment by sarbbottam** [comment]
Sounds good!
