### ISSUE TITLE
Switch to the getRules API instead of reading the directory contents

### ISSUE THREAD

**Issue by mgol** [sarbbottam/eslint-find-rules#211]
Now that https://github.com/eslint/eslint/pull/7669 has landed this tool can switch to the new `getRules()` API and stop reading the ESLint package contents (unless the API is not available, i.e. for older ESLint versions).

This will make the tools independent of ESLint potentially changing its package structure which is private and would make it possible to add features like #172.

**Comment by ljharb** [comment]
Probably best to avoid two code paths, and up the required eslint version in a breaking change.

**Comment by randycoulman** [comment]
I started to work on this, but very quickly ran into a dependency issue.  In order to require a minimum version of ESLint 3.12.0, we also need to upgrade to a newer version of eslint-config-kentcdodds.  In order to get support for ESLint 3.x, we need at least version 7.0.0 (we're at 6.2.0).  But upgrading that dependency results in numerous lint errors, because this codebase no longer conforms to the latest rules in that config.  At first glance, it looks like a lot of the updated rules are looking to take advantage of ES6 features.  

As I understand it, ES6 conversion of this project is ongoing in #200, and part of that PR moves us over to xo instead of eslint.

How would you like to address this issue?  Does it need to wait for #200 to land?  If so, when is that likely to happen?  Is there any way I can help move it along?
